### ISSUE TITLE
Where does Verbose Output go?

### ISSUE THREAD

**Issue by Raildex** [ksgfk/EmbreeSharp#2]

**Comment by ksgfk** [comment]
I haven't used the verbose output feature of Embree. In the Embree source code, it is output using the standard input/output stream std::cerr, which prints directly to the console. If you want to obtain verbose information, you might consider using the rtcSetDeviceErrorFunction function.

By the way, this library will not be maintained for the time being. :(

**Comment by ksgfk** [comment]
In the new version, when enable verbose, embree will output to standard IO.

See example in `Samples/EmbreeInfo`
