### ISSUE TITLE
Where are the RTCRayHitN_ helper functions?

### ISSUE THREAD

**Issue by Raildex** [ksgfk/EmbreeSharp#3]
When receiving a callback through `RTCFilterFunctionNArguments*`, previously we could use helper functions such as 
```
var geomID = *RTCHitN_geomID(args->hit, args->N, (uint)i);
var primID = *RTCHitN_primID(args->hit, args->N, (uint)i);
```

the RTCHitN_ helper functions return values of a particular ray of a ray packet.
These functions are missing in the newest version.

**Comment by ksgfk** [comment]
Because I hope to provide safe wrapper in C # for the `SetGeometry[Intersect/Occluded/Bounds]Function` series. So I ignored them

I will add them in the next version.

**Comment by ksgfk** [comment]
I add all missing helper functions in class `EmbreeSharp.Native.EmbreeNative`.

You can use them in version `v0.6.3`

But these functions are not tested. If you find any problem, please open a new issue
